POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
    "username": "jim",
    "password": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username": "jest",
    "password": "123456"
}


### 
POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjc4MjgxNjY1NTJmNzllYjk0NzU5NzEiLCJpYXQiOjE2NTIwNDE3NTB9.UJfO5MDHFQm6zEfOeZ_-qTKHcrFNaGKvPcriheCy2gA


{
    "title" :"JAVA3",
    "description": "java3",
    "url": "java.com",
    "status": "LEARNING"
}

### 
GET http://localhost:5000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjc4MjgxNjY1NTJmNzllYjk0NzU5NzEiLCJpYXQiOjE2NTIwNDE3NTB9.UJfO5MDHFQm6zEfOeZ_-qTKHcrFNaGKvPcriheCy2gA


### 
PUT http://localhost:5000/api/post/627d5c64615243cdbac165a9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjc4MjgxNjY1NTJmNzllYjk0NzU5NzEiLCJpYXQiOjE2NTIwNDE3NTB9.UJfO5MDHFQm6zEfOeZ_-qTKHcrFNaGKvPcriheCy2gA

{
    "title": "Vue",
    "description": "VUEEE",
    "url" : "vue.org",
    "status" : "LEARNING"
}