POST http://localhost:3000/api/auth/register
Content-Type: application/json


{
    "username": "thaocho2",
    "password": "123456"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
    "username": "thaocho",
    "password": "123456"
}


### 
POST http://localhost:3000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjc4MjgxNjY1NTJmNzllYjk0NzU5NzEiLCJpYXQiOjE2NTIwNDE3NTB9.UJfO5MDHFQm6zEfOeZ_-qTKHcrFNaGKvPcriheCy2gA


{
    "title" :"JAVA3",
    "description": "java3",
    "url": "java.com",
    "status": "LEARNING"
}

### 
GET http://localhost:3000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjc4MjgxNjY1NTJmNzllYjk0NzU5NzEiLCJpYXQiOjE2NTIwNDE3NTB9.UJfO5MDHFQm6zEfOeZ_-qTKHcrFNaGKvPcriheCy2gA


### 
PUT http://localhost:3000/api/post/627d5c64615243cdbac165a9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjc4MjgxNjY1NTJmNzllYjk0NzU5NzEiLCJpYXQiOjE2NTIwNDE3NTB9.UJfO5MDHFQm6zEfOeZ_-qTKHcrFNaGKvPcriheCy2gA

{
    "title": "Vue",
    "description": "VUEEE",
    "url" : "vue.org",
    "status" : "LEARNING"
}

###
POST http://localhost:3000/api/userInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjliNmZjZWFmYThlMGE5OGEyZmQyMTYiLCJpYXQiOjE2NTQzNTQwMjV9.THBwinJYTrPWG_HyOsiyP1ouklxn7aykiLHsLrHYZaQ

{
    "idNo" : "281208117",
    "fullname" : "Nguyen Thi Thao",
    "birthday" : "20/08/1998",
    "address" : "603A DT743, Dong Tan, Di An, Binh Duong",
    "phone" : "0908714130",
    "avatar" : ""
}